name: Hello World Workflow

on: 
  push:
    branches:
      - feature/folder-structure-frontend 
  pull_request:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Imprimir un mensaje
        run: echo "¡Hola, GitHub Actions está funcionando!"
