name: Restrict PR Approvals

on:
  pull_request:
    types: [submitted]  # Se ejecuta cuando alguien aprueba un PR

jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener aprobaciones del PR
        id: get-approvals
        run: |
          REVIEWERS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
            | jq -r '.[] | select(.state=="APPROVED") | .user.login')

          echo "Aprobadores encontrados: $REVIEWERS"

          ALLOWED_USERS=("maintainer1" "maintainer2" "maintainer3")  # Reemplaza con los Maintainers

          for reviewer in $REVIEWERS; do
            if [[ ! " ${ALLOWED_USERS[@]} " =~ " ${reviewer} " ]]; then
              echo "⚠️ El usuario $reviewer no tiene permiso para aprobar PRs."
              exit 1
            fi
          done

      - name: Permitir Merge
        run: echo "✅ La aprobación es válida. Se puede proceder con el merge."
